# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoidHeightCorrector
                                 A QGIS plugin
 Convert ETR89 ellipsoid hegiht to DVR90 reference geoid height
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-07-13
        copyright            : (C) 2024 by AestasGIS
        email                : bvt@aestas.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'AestasGIS'
__date__ = '2024-07-13'
__copyright__ = '(C) 2024 by AestasGIS'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoidHeightCorrector class from file GeoidHeightCorrector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geoid_height_corrector import GeoidHeightCorrectorPlugin
    return GeoidHeightCorrectorPlugin()
